var currentIndex = 0;
function changeBg(){
    var bgImgs = ["2.jpg","3.jpg","1.jpg"];
	var ol1=document.getElementById('s-l-1');
	var ol2=document.getElementById('s-l-2');
	var ol3=document.getElementById('s-l-3');
	var ol4=document.getElementById('s-l-4');
	var ol5=document.getElementById('s-l-5');
	var ol6=document.getElementById('s-l-6');
	var ol7=document.getElementById('s-l-7');
	var ol8=document.getElementById('s-l-8');
	var ol9=document.getElementById('s-l-9');
    var s1=document.getElementById('shadow1');
    var s2=document.getElementById('shadow2');
    var s3=document.getElementById('shadow3');
    if (currentIndex >= bgImgs.length)
                currentIndex = 0;
	s1.style.display='none';
	s2.style.display='none';
	s3.style.display='none';
	ol1.style.backgroundColor='gray';
	ol2.style.backgroundColor='gray';
	ol3.style.backgroundColor='gray';
	ol4.style.backgroundColor='gray';
	ol5.style.backgroundColor='gray';
	ol6.style.backgroundColor='gray';
	ol7.style.backgroundColor='gray';
	ol8.style.backgroundColor='gray';
	ol9.style.backgroundColor='gray';
    var obj = document.getElementById('pic');
    var a="url(img/"+bgImgs[currentIndex]+")";
    obj.style.backgroundImage=a;
	if(currentIndex==0){
		s2.style.display='block';
		ol5.style.backgroundColor='#0094f2';
	}else if(currentIndex==1){
		s3.style.display='block';
		ol9.style.backgroundColor='#0094f2';
	}else{
		s1.style.display='block';
		ol1.style.backgroundColor='#0094f2';
	}
    currentIndex += 1; 
}
setInterval("changeBg()", 3000);
window.onload=function(){
	var ol1=document.getElementById('s-l-1');
	var ol2=document.getElementById('s-l-2');
	var ol3=document.getElementById('s-l-3');
	var ol4=document.getElementById('s-l-4');
	var ol5=document.getElementById('s-l-5');
	var ol6=document.getElementById('s-l-6');
	var ol7=document.getElementById('s-l-7');
	var ol8=document.getElementById('s-l-8');
	var ol9=document.getElementById('s-l-9');
	var s1=document.getElementById('shadow1');
    var s2=document.getElementById('shadow2');
    var s3=document.getElementById('shadow3');
	ol1.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/1.jpg)";
  	    obj.style.backgroundImage=a;
		s1.style.display='block';
		ol1.style.backgroundColor='#0094f2';
	}
	ol2.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/2.jpg)";
  	    obj.style.backgroundImage=a;
		s2.style.display='block';
		ol5.style.backgroundColor='#0094f2';
	}
	ol3.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/3.jpg)";
  	    obj.style.backgroundImage=a;
		s3.style.display='block';
		ol9.style.backgroundColor='#0094f2';
	}
	ol4.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/1.jpg)";
  	    obj.style.backgroundImage=a;
		s1.style.display='block';
		ol1.style.backgroundColor='#0094f2';
	}
	ol5.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/2.jpg)";
  	    obj.style.backgroundImage=a;
		s2.style.display='block';
		ol5.style.backgroundColor='#0094f2';
	}
	ol6.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/3.jpg)";
  	    obj.style.backgroundImage=a;
		s3.style.display='block';
		ol9.style.backgroundColor='#0094f2';
	}
	ol7.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/1.jpg)";
  	    obj.style.backgroundImage=a;
		s1.style.display='block';
		ol1.style.backgroundColor='#0094f2';
	}
	ol8.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/2.jpg)";
  	    obj.style.backgroundImage=a;
		s2.style.display='block';
		ol5.style.backgroundColor='#0094f2';
	}
	ol9.onmouseover=function(){
		s1.style.display='none';
		s2.style.display='none';
		s3.style.display='none';
		ol1.style.backgroundColor='gray';
		ol2.style.backgroundColor='gray';
		ol3.style.backgroundColor='gray';
		ol4.style.backgroundColor='gray';
		ol5.style.backgroundColor='gray';
		ol6.style.backgroundColor='gray';
		ol7.style.backgroundColor='gray';
		ol8.style.backgroundColor='gray';
		ol9.style.backgroundColor='gray';
 	    var obj = document.getElementById('pic');
 	    var a="url(img/3.jpg)";
  	    obj.style.backgroundImage=a;
		s3.style.display='block';
		ol9.style.backgroundColor='#0094f2';
	}
}
